name: Build briloner-mqtt-gateway

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure full history for git diff to work

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push multi-platform Docker image
      run: |
        docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${GITHUB_REPOSITORY,,}/briloner-mqtt-gateway:latest \
          -f ./dockerfiles/meshgateway/Dockerfile \
          --target production --push

